In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in c:\users\shaiv\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\shaiv\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shaiv\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shaiv\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shaiv\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\shaiv\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [97]:
import pandas as pd
import numpy as np

In [99]:
customers=pd.read_csv(r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\raw\olist_customers_dataset.csv")
orders=pd.read_csv(r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\raw\olist_orders_dataset.csv")
payments=pd.read_csv(r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\raw\olist_order_payments_dataset.csv")
reviews=pd.read_csv(r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\raw\olist_order_reviews_dataset.csv")
items=pd.read_csv(r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\raw\olist_order_items_dataset.csv")

In [100]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [101]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [102]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [103]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [104]:
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [105]:
print(customers.shape)
print(orders.shape)
print(payments.shape)
print(reviews.shape)
print(items.shape)

(99441, 5)
(99441, 8)
(103886, 5)
(99224, 7)
(112650, 7)

In [106]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [107]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [108]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [114]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [120]:
items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [121]:
customers = customers[
    [
    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state"
    ]
    ]

In [125]:
payments = payments[
    [
        "order_id",
        "payment_sequential",
        "payment_type",
        "payment_installments",
        "payment_value"
    ]
]

In [127]:
reviews = reviews[
    [
        "order_id",
        "review_score"
    ]
    ]

In [129]:
items = items[
    [
        "order_id",
        "price",
        "freight_value"
    ]
]

In [131]:
orders["order_purchase_timestamp"]=pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_delivered_customer_date"]=pd.to_datetime(orders["order_delivered_customer_date"])
orders["order_estimated_delivery_date"]=pd.to_datetime(orders["order_estimated_delivery_date"])
orders["order_approved_at"]=pd.to_datetime(orders["order_approved_at"])
orders["order_delivered_carrier_date"]=pd.to_datetime(orders["order_delivered_carrier_date"])

In [133]:
#delay feature
orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_estimated_delivery_date"]
).dt.days

In [135]:
#aggregate payments
payments_agg = payments.groupby("order_id").agg(
    {
        "payment_value":"sum",
        "payment_installments":"max",
        "payment_sequential":"max"
    }
).reset_index()

In [137]:
#aggregate items
items_agg = items.groupby("order_id").agg(
    {
        "price":"sum",
        "freight_value":"sum"
    }
).reset_index()

In [139]:
#payment retry flag
payments_agg["payment_retry_flag"]=(
    payments_agg["payment_sequential"]>1)

In [141]:
#approval delay
orders["approval_delay_hours"]=(
    orders["order_approved_at"]-orders["order_purchase_timestamp"]
).dt.total_seconds()/3600

In [143]:
#merge customers+orders
df = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

In [145]:
#merge payment new features
df = df.merge(
    payments_agg,
    on="order_id",
    how="left"
)

In [147]:
#merge reviews
df = df.merge(
    reviews,
    on="order_id",
    how="left"
)

In [149]:
df=df.merge(
    items_agg,
    on="order_id",
    how="left"
)

In [151]:
df.head()

,customer_id,customer_unique_id,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,approval_delay_hours,payment_value,payment_installments,payment_sequential,payment_retry_flag,review_score,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,-11.0,0.276944,146.87,2.0,1.0,False,4.0,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,-8.0,0.168889,335.48,8.0,1.0,False,5.0,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,1.0,24.190278,157.73,7.0,1.0,False,5.0,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,-13.0,1.378056,173.30,1.0,1.0,False,5.0,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,-6.0,0.310833,252.25,8.0,1.0,False,5.0,230.00,22.25

In [153]:
df["payment_retry_flag"] = (
    df["payment_retry_flag"]
    .fillna(0)
    .astype(int)
)

In [155]:
df.head()

,customer_id,customer_unique_id,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,approval_delay_hours,payment_value,payment_installments,payment_sequential,payment_retry_flag,review_score,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,-11.0,0.276944,146.87,2.0,1.0,0,4.0,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,-8.0,0.168889,335.48,8.0,1.0,0,5.0,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,1.0,24.190278,157.73,7.0,1.0,0,5.0,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,-13.0,1.378056,173.30,1.0,1.0,0,5.0,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,-6.0,0.310833,252.25,8.0,1.0,0,5.0,230.00,22.25

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99992 entries, 0 to 99991
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    99992 non-null  object
 1   customer_unique_id             99992 non-null  object
 2   customer_city                  99992 non-null  object
 3   customer_state                 99992 non-null  object
 4   order_id                       99992 non-null  object
 5   order_status                   99992 non-null  object
 6   order_purchase_timestamp       99992 non-null  datetime64[ns]
 7   order_approved_at              99831 non-null  datetime64[ns]
 8   order_delivered_carrier_date   98199 non-null  datetime64[ns]
 9   order_delivered_customer_date  97005 non-null  datetime64[ns]
 10  order_estimated_delivery_date  99992 non-null  datetime64[ns]
 11  delivery_delay_days            97005 non-null  float64
 12  approval_delay_hours           99831 non-null  float64
 13  payment_value                  99991 non-null  float64
 14  payment_installments           99991 non-null  float64
 15  payment_sequential             99991 non-null  float64
 16  payment_retry_flag             99992 non-null  int32
 17  review_score                   99224 non-null  float64
 18  price                          99214 non-null  float64
 19  freight_value                  99214 non-null  float64
dtypes: datetime64[ns](5), float64(8), int32(1), object(6)
memory usage: 14.9+ MB

In [159]:
df.shape

(99992, 20)

In [161]:
df["payment_installments"] = (
    df["payment_installments"]
    .fillna(0)
    .astype(int)
)

In [163]:
df["payment_installments"].dtype

dtype('int32')

Behavioural analytics

In [166]:
purchase_frequency = df.groupby(
    "customer_unique_id")["order_id"].count().reset_index()

purchase_frequency.columns=[
    "customer_unique_id",
    "purchase_frequency"
]

In [168]:
total_spend=df.groupby(
    "customer_unique_id")["payment_value"].sum().reset_index()

total_spend.columns=[
    "customer_unique_id",
    "total_spend"
]

In [170]:
#avg order value = total revenue/orders
aov=df.groupby("customer_unique_id")["payment_value"].mean().reset_index()

aov.columns=[
    "customer_unique_id",
    "average_order_value"
]

In [172]:
df = df.merge(
    purchase_frequency,
    on="customer_unique_id",
    how="left"
)

In [174]:
df = df.merge(
    total_spend,
    on="customer_unique_id",
    how="left"
)

In [176]:
df = df.merge(
    aov,
    on="customer_unique_id",
    how="left"
)

In [178]:
df["customer_segment"] = pd.qcut(
    df["total_spend"],
    q=3,
    labels=["Low Value", "Medium Value", "High Value"]
)

In [180]:
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_city', 'customer_state',
       'order_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_delay_days', 'approval_delay_hours', 'payment_value',
       'payment_installments', 'payment_sequential', 'payment_retry_flag',
       'review_score', 'price', 'freight_value', 'purchase_frequency',
       'total_spend', 'average_order_value', 'customer_segment'],
      dtype='object')

In [182]:
df.head()

,customer_id,customer_unique_id,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,...,payment_installments,payment_sequential,payment_retry_flag,review_score,price,freight_value,purchase_frequency,total_spend,average_order_value,customer_segment
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,...,2,1.0,0,4.0,124.99,21.88,1,146.87,146.87,Medium Value
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,...,8,1.0,0,5.0,289.00,46.48,1,335.48,335.48,High Value
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,...,7,1.0,0,5.0,139.94,17.79,1,157.73,157.73,Medium Value
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,...,1,1.0,0,5.0,149.94,23.36,1,173.30,173.30,High Value
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,...,8,1.0,0,5.0,230.00,22.25,1,252.25,252.25,High Value

In [184]:
df.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,approval_delay_hours,payment_value,payment_installments,payment_sequential,payment_retry_flag,review_score,price,freight_value,purchase_frequency,total_spend,average_order_value
count,99992,99831,98199,97005,99992,97005.000000,99831.000000,99991.000000,99992.000000,99991.000000,99992.000000,99224.000000,99214.000000,99214.000000,99992.000000,99992.000000,99991.000000
mean,2017-12-31 01:03:16.518251776,2017-12-31 10:57:04.827168256,2018-01-04 14:06:56.121141760,2018-01-14 04:26:12.785742848,2018-01-23 19:42:38.220657408,-11.880790,10.422975,160.828682,2.934015,1.045664,0.030552,4.086421,137.600777,22.818845,1.103168,175.584281,160.828682
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00,-147.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.850000,0.000000,1.000000,0.000000,0.000000
25%,2017-09-12 08:42:07,2017-09-12 16:07:44,2017-09-15 19:55:26,2017-09-25 20:06:58,2017-10-03 00:00:00,-17.000000,0.215000,61.990000,1.000000,1.000000,0.000000,4.000000,45.900000,13.850000,1.000000,64.290000,62.750000
50%,2018-01-18 16:44:29,2018-01-19 01:39:19,2018-01-24 01:09:36,2018-02-02 16:06:39,2018-02-15 00:00:00,-12.000000,0.343333,105.280000,2.000000,1.000000,0.000000,5.000000,86.800000,17.170000,1.000000,112.300000,105.940000
75%,2018-05-04 09:51:55,2018-05-04 13:50:50,2018-05-08 12:03:30,2018-05-15 20:02:44,2018-05-25 00:00:00,-7.000000,14.596944,176.830000,4.000000,1.000000,0.000000,5.000000,149.900000,24.050000,1.000000,192.455000,176.880000
max,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12 00:00:00,188.000000,4509.180556,13664.080000,24.000000,29.000000,1.000000,5.000000,13440.000000,1794.960000,17.000000,13664.080000,13664.080000
std,NaN,NaN,NaN,NaN,NaN,10.183992,26.005654,221.580101,2.718829,0.383914,0.172103,1.347579,210.284622,21.624222,0.481641,247.211570,220.286268

In [186]:
df.isnull().sum()

customer_id                         0
customer_unique_id                  0
customer_city                       0
customer_state                      0
order_id                            0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1793
order_delivered_customer_date    2987
order_estimated_delivery_date       0
delivery_delay_days              2987
approval_delay_hours              161
payment_value                       1
payment_installments                0
payment_sequential                  1
payment_retry_flag                  0
review_score                      768
price                             778
freight_value                     778
purchase_frequency                  0
total_spend                         0
average_order_value                 1
customer_segment                    0
dtype: int64

In [188]:
df.to_csv(
    r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\processed/base_customer_behavior_dataset.csv",
    index=False
)