In [4]:
import pandas as pd

In [6]:
df=pd.read_csv(r"C:\Users\shaiv\Downloads\data analytics projects\bayesian_ab_testing_platform\data\experiments/ab_experiment_dataset.csv")

In [7]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

In [8]:
from src.eda import *
from src.frequentist import *
from src.bayesian import *
from src.early_stopping import *
from src.decision_engine import *

In [5]:
df.head()

,customer_id,customer_unique_id,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,...,total_spend,average_order_value,customer_segment,variant,base_conversion_prob,converted,base_click_prob,clicked,experiment_revenue,device_type
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,...,146.87,146.87,Medium Value,A,0.067,0,0.125,0,146.870000,Mobile
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,...,335.48,335.48,High Value,B,0.135,0,0.177,0,351.440870,Desktop
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,...,157.73,157.73,Medium Value,B,0.090,0,0.150,0,167.394162,Tablet
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,...,173.30,173.30,High Value,A,0.097,0,0.155,0,173.300000,Mobile
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,...,252.25,252.25,High Value,A,0.097,0,0.155,0,252.250000,Mobile

In [6]:
get_variant_distribution(df)

  variant  proportion
0       A    0.701086
1       B    0.298914

In [7]:
conversion_rates(df)

  variant  converted
0       A   0.066146
1       B   0.098063

In [8]:
get_ctr_rates(df)

  variant   clicked
0       A  0.123076
1       B  0.150490

In [9]:
get_revenue_metrics(df)

  variant  experiment_revenue
0       A          160.973982
1       B          169.310914

In [10]:
get_device_conversion(df)

  variant device_type  converted
0       A     Desktop   0.072749
1       A      Mobile   0.063926
2       A      Tablet   0.064210
3       B     Desktop   0.105073
4       B      Mobile   0.095274
5       B      Tablet   0.102082

In [11]:
get_segment_conversion(df)

  variant customer_segment  converted
0       A       High Value   0.094985
1       A        Low Value   0.036748
2       A     Medium Value   0.066532
3       B       High Value   0.134207
4       B        Low Value   0.064904
5       B     Medium Value   0.095607

In [12]:
calculate_conversion_test(df)

(-17.46826922814005, 2.4996313358356406e-68)

In [13]:
calculate_ctr_test(df)

(-11.751397816347765, 6.946023740984026e-32)

In [14]:
calculate_revenue_test(df)

(-5.031035605261271, 4.895369191801724e-07)

In [15]:
calculate_posteriors(df)

(4638, 65467, 2932, 26959)

In [16]:
probability_b_wins(df)

1.0

In [17]:
credible_interval(df)

(0.02811997369917799, 0.035803871587181756)

In [18]:
result = confidence_curve(df)
print(result)

   traffic_pct  prob_b_better
0          1.0        0.98515
1          2.0        0.97623
2          5.0        0.99860
3         10.0        1.00000
4         15.0        1.00000
5         20.0        1.00000
6         30.0        1.00000
7         40.0        1.00000
8         50.0        1.00000
9        100.0        1.00000

In [11]:
find_early_stop(df)

1.0

In [14]:
users_saved(df)

98993

In [16]:
recommend_action(df)

'Deploy Variant B'

In [18]:
executive_summary(df)

'\n    ===== EXECUTIVE SUMMARY =====\n\n    Probability B Wins: 100.00%\n\n    Conversion P-Value: 2.4996e-68\n\n    CTR P-Value: 6.9460e-32\n\n    Revenue P-Value: 4.8954e-07\n\n    Early Stop Point: 1.0% traffic\n\n    Users Saved: 98,993\n\n    Risk Level: Low\n\n    Recommendation: Deploy Variant B\n\n    =============================\n    '